function generateStatusSummary(alerts) {
  const down = alerts.filter((a) => a.currentStatus === "DOWN");
  const frozen = alerts.filter((a) => a.currentStatus === "FROZEN");
  const degraded = alerts.filter((a) => a.currentStatus === "DEGRADED");
  const recovered = alerts.filter((a) => a.currentStatus === "UP");

  // Helper function to build stylized sections to keep the template literal clean
  const buildSection = (items, title, color) => {
    if (items.length === 0) return "";
    return `
      <div style="margin-bottom: 24px;">
        <h2 style="color: ${color}; font-size: 16px; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid ${color}; padding-bottom: 5px;">
          ${title} (${items.length})
        </h2>
        <ul style="list-style: none; padding: 0; margin: 0;">
          ${items
            .map(
              (c) => `
            <li style="background: #fdfdfd; border: 1px solid #eaeaea; border-left: 4px solid ${color}; border-radius: 4px; padding: 12px; margin-bottom: 8px;">
  <div style="font-weight:600;">
    ${c.name}
  </div>

  <div style="font-size:13px;color:#64748b;margin-top:4px;">
    📍 ${c.location}
  </div>

  <div style="font-size:13px;margin-top:4px;">
    ${c.previousStatus} → ${c.currentStatus}
  </div>
</li>
          `,
            )
            .join("")}
        </ul>
      </div>
    `;
  };

  return `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f1f5f9; padding: 40px 10px;">
      <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); overflow: hidden;">
        
        <!-- Header -->
        <div style="background-color: #0f172a; padding: 24px; text-align: center;">
          <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">
            HLS Monitoring Summary
          </h1>
        </div>

        <!-- Body -->
        <div style="padding: 30px;">
          ${buildSection(down, "Down Channels", "#ef4444")}      <!-- Red -->
          ${buildSection(frozen, "Frozen Channels", "#f59e0b")}  <!-- Orange -->
		   ${buildSection(degraded, "Degraded Channels", "#eab308")}
          ${buildSection(recovered, "Recovered Channels", "#10b981")} <!-- Green -->
        </div>

        <!-- Footer -->
        <div style="background-color: #f8fafc; padding: 16px; text-align: center; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px;">
          Automated alert generated by Stream Monitoring Server
        </div>
        
      </div>
    </div>
  `;
}

module.exports = {
  generateStatusSummary,
};
