function generateAlertEmail(stream, previousStatus, currentStatus) {
  // Determine color and icon based on the new status
  let statusColor = "#64748b"; // Default slate
  let icon = "🔔";

  if (currentStatus === "UP") {
    statusColor = "#10b981"; // Green
    icon = "🟢";
  } else if (currentStatus === "DOWN") {
    statusColor = "#ef4444"; // Red
    icon = "🔴";
  } else if (currentStatus === "FROZEN") {
    statusColor = "#f59e0b"; // Orange
    icon = "🟠";
  }

  return `
    <div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f1f5f9; padding: 40px 10px;">
      <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); overflow: hidden;">
        
        <div style="background-color: #0f172a; padding: 24px; text-align: center; border-bottom: 4px solid ${statusColor};">
          <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">
            ${icon} Stream Status Alert
          </h1>
        </div>

        <div style="padding: 32px 40px;">
          <p style="color: #333333; font-size: 15px; margin-top: 0; margin-bottom: 24px; line-height: 1.5;">
            The monitoring system has detected a state change for <strong>${stream.name}</strong>.
          </p>

          <table width="100%" cellpadding="14" cellspacing="0" style="border-collapse: collapse; font-size: 14px; background-color: #f8fafc; border-radius: 6px; overflow: hidden; border: 1px solid #e2e8f0;">
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="color: #64748b; font-weight: 600; width: 40%;">Channel</td>
              <td style="color: #0f172a; font-weight: bold;">${stream.name}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="color: #64748b; font-weight: 600;">Previous Status</td>
              <td style="color: #64748b;">${previousStatus}</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
              <td style="color: #64748b; font-weight: 600;">Current Status</td>
              <td style="color: ${statusColor}; font-weight: bold; font-size: 15px;">${currentStatus}</td>
            </tr>
            <tr>
              <td style="color: #64748b; font-weight: 600;">Event Time</td>
              <td style="color: #0f172a;">${new Date().toLocaleString()}</td>
            </tr>
          </table>
        </div>

        <div style="background-color: #f8fafc; padding: 16px; text-align: center; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px;">
          Automated alert generated by Stream Monitoring Server
        </div>
        
      </div>
    </div>
  `;
}

module.exports = {
  generateAlertEmail,
};
